# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [1]:
import numpy
from keras.datasets import cifar100
import numpy as np
np.random.seed(100)

# 資料準備

# Image normalize 

# 轉換label 為OneHot Encoding

In [2]:
(x_train, y_train), (x_test, y_test) = cifar100.load_data()
print('train: ',len(x_train))
print('test : ',len(x_test))

169009152/169001437 [==============================] - 91s 1us/step
train:  50000
test :  10000


In [3]:
print('shape of ~')
print('x_train: ',x_train.shape)
print('y_train: ',y_train.shape)
print('x_test : ',x_test.shape)
print('y_test : ',y_test.shape)

shape of ~
x_train:  (50000, 32, 32, 3)
y_train:  (50000, 1)
x_test :  (10000, 32, 32, 3)
y_test :  (10000, 1)


In [7]:
x_train[0][0][0]

array([255, 255, 255], dtype=uint8)

In [9]:
x_train_norm = x_train.astype('float32') / 255.
x_test_norm = x_test.astype('float32') / 255.
x_train_norm[0][0][0]

array([1., 1., 1.], dtype=float32)

In [10]:
y_train[0]

array([19])

In [12]:
from keras.utils import np_utils
y_train_OneHot = np_utils.to_categorical(y_train)
y_test_OneHot = np_utils.to_categorical(y_test)
y_train_OneHot[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)